Repository CaZaIt/CaZaIt-Server, pull requests merged in 2023-08, with the labels that each got.

#338 카페 UUID 적용
  src/main/java/shop/cazait/domain/cafe/api/CafeManageApiController.java
  src/main/java/shop/cazait/domain/cafe/api/CafeSearchApiController.java
  src/main/java/shop/cazait/domain/cafe/model/dto/response/CafeCreateOutDTO.java
  src/main/java/shop/cazait/domain/cafe/model/dto/response/CafeGetOutDTO.java
  src/main/java/shop/cazait/domain/cafe/model/dto/response/CafeListOutDTO.java
  src/main/java/shop/cazait/domain/cafe/model/dto/response/CafeUpdateOutDTO.java
  src/main/java/shop/cazait/domain/cafe/model/dto/response/ManageCafeListOutDTO.java
  src/main/java/shop/cazait/domain/cafe/model/entity/Cafe.java
  src/main/java/shop/cazait/domain/cafe/repository/CafeRepository.java
  src/main/java/shop/cazait/domain/cafe/service/CafeManageService.java
  src/main/java/shop/cazait/domain/cafe/service/CafeSearchService.java
  src/main/java/shop/cazait/domain/cafeimage/dto/request/CafeImageCreateInDTO.java
  src/main/java/shop/cazait/domain/cafeimage/repository/CafeImageRepository.java
  src/main/java/shop/cazait/domain/cafeimage/service/CafeImageService.java
  src/main/java/shop/cazait/domain/checklog/api/CheckLogApiController.java
  src/main/java/shop/cazait/domain/checklog/dto/GetCheckLogRes.java
  src/main/java/shop/cazait/domain/checklog/dto/PostCheckLogRes.java
  src/main/java/shop/cazait/domain/checklog/entity/CheckLog.java
  src/main/java/shop/cazait/domain/checklog/repository/CheckLogRepository.java
  src/main/java/shop/cazait/domain/checklog/service/CheckLogService.java
  src/main/java/shop/cazait/domain/congestion/api/CongestionApiController.java
  src/main/java/shop/cazait/domain/congestion/dto/response/CongestionUpdateOutDTO.java
  src/main/java/shop/cazait/domain/congestion/service/CongestionService.java
  src/main/java/shop/cazait/domain/favorites/api/FavoritesApiController.java
  src/main/java/shop/cazait/domain/favorites/dto/response/FavoritesListOutDTO.java
  src/main/java/shop/cazait/domain/favorites/repository/FavoritesRepository.java
  src/main/java/shop/cazait/domain/favorites/service/FavoritesService.java
  src/main/java/shop/cazait/domain/menu/dto/request/MenuCreateInDTO.java
  src/main/java/shop/cazait/domain/menu/dto/response/MenuUpdateOutDTO.java
  src/main/java/shop/cazait/domain/menu/service/MenuService.java
Labels: 📬 API, 🔨 Refactor

#343 카페 ID 조회 시 즐겨찾기 여부 반환
  src/main/java/shop/cazait/domain/cafe/api/CafeSearchApiController.java
  src/main/java/shop/cazait/domain/cafe/model/dto/response/CafeGetOutDTO.java
  src/main/java/shop/cazait/domain/cafe/model/dto/response/CafeListOutDTO.java
  src/main/java/shop/cazait/domain/cafe/service/CafeSearchService.java
  src/main/java/shop/cazait/domain/favorites/entity/FavoritesStatus.java
Labels: 📬 API, 🔨 Refactor

#344 카페 ID 조회 API 분리
  src/main/java/shop/cazait/domain/cafe/api/CafeSearchApiController.java
  src/main/java/shop/cazait/domain/cafe/model/dto/response/CafeGetOutDTO.java
  src/main/java/shop/cazait/domain/cafe/service/CafeSearchService.java
  src/main/java/shop/cazait/domain/favorites/repository/FavoritesRepository.java
Labels: 📬 API, 🔨 Refactor

#340 유저 아이디/비밀번호 수정 API 및 DTO 리팩토링
  src/main/java/shop/cazait/domain/auth/api/AuthController.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthSendAuthNumberCodeInDTO.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthSendMessageCodeInFindAccountNameInDTO.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthSendMessageCodeInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/dto/UserEnterAccountNameInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserEnterAccountNameInResetPasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserFindExistAccountNameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserFindExistNicknameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserFindExistPhoneNumberInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserUpdatePasswordInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserUpdatePasswordInResetPasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserVerifyUserInfoInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserVerifyUserInfoInResetPasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
  src/main/java/shop/cazait/global/error/status/ErrorStatus.java
  src/main/java/shop/cazait/global/error/status/SuccessStatus.java
Labels: 🐞 BugFix, 🔨 Refactor, 📚Swagger

#345 [Refactor] #341 - Menu 관련 API 수정
  src/main/java/shop/cazait/domain/menu/api/MenuApiController.java
  src/main/java/shop/cazait/domain/menu/dto/response/MenuListOutDTO.java
  src/main/java/shop/cazait/domain/menu/dto/response/MenuUpdateOutDTO.java
  src/main/java/shop/cazait/domain/menu/repository/MenuRepository.java
  src/main/java/shop/cazait/domain/menu/service/MenuService.java
Labels: 🔨 Refactor

#348 유저, 인증 박싱 타입 -> 기본 타입
  src/main/java/shop/cazait/domain/auth/api/AuthController.java
  src/main/java/shop/cazait/domain/auth/dto/kakao/ExtKakaoUserInfoOutDTO.java
  src/main/java/shop/cazait/domain/auth/dto/kakao/ExtKakaoUserTokenOutDTO.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthSendMessageCodeTestOutDTO.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthVerifyMessageCodeInDTO.java
  src/main/java/shop/cazait/domain/auth/service/AuthService.java
  src/main/java/shop/cazait/domain/auth/service/KakaoService.java
  src/main/java/shop/cazait/domain/user/entity/User.java
  src/main/java/shop/cazait/domain/user/repository/UserRepository.java
Labels: 🔨 Refactor

#350 유저 아이디 , 비밀번호 수정 API 리팩토링 (2차)
  src/main/java/shop/cazait/domain/auth/api/AuthController.java
  src/main/java/shop/cazait/domain/auth/service/KakaoService.java
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/dto/UserUpdateInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserUpdatePasswordInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserCreateInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserFindAccountNameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserFindExistAccountNameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserFindExistNicknameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserFindExistPhoneNumberInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserUpdateNicknameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserUpdatePasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserVerifyPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserVerifyUserInfoInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/response/UserCreateOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/response/UserDeleteOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/response/UserFindAccountNameOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/response/UserFindOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/response/UserUpdateNicknameOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/response/UserUpdatePasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/response/UserVerifyPasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/response/UserVerifyUserInfoInResetPasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/entity/User.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
  src/main/java/shop/cazait/global/config/encrypt/WebConfig.java
  src/main/java/shop/cazait/global/error/status/ErrorStatus.java
Labels: 🔨 Refactor

#351 [Fix] #347 - kakaoId 박싱
  src/main/java/shop/cazait/domain/auth/api/AuthController.java
  src/main/java/shop/cazait/domain/auth/service/KakaoService.java
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/entity/User.java
  src/main/java/shop/cazait/domain/user/repository/UserRepository.java
Labels: 🐞 BugFix

#353 유저 정규식 검증 수정 및 추가
  src/main/java/shop/cazait/domain/auth/dto/UserAuthenticateInDTO.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthSendAuthNumberCodeInDTO.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthVerifyMessageCodeInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserCreateInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserFindAccountNameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserFindExistAccountNameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserFindExistPhoneNumberInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserUpdateNicknameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserUpdatePasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserVerifyPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserVerifyUserInfoInResetPasswordInDTO.java
Labels: 🔨 Refactor, 📚Swagger

#354 정규식 @Valid 추가
  src/main/java/shop/cazait/domain/auth/api/AuthController.java
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
Labels: 🐞 BugFix, ✨ Feature

#356 인증번호 validation 오류 수정
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthVerifyMessageCodeInDTO.java
Labels: 🐞 BugFix

#357 DTO에 닉네임 정규식 추가
  src/main/java/shop/cazait/domain/user/dto/request/UserCreateInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserFindExistNicknameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/request/UserUpdateNicknameInDTO.java
Labels: 🔨 Refactor

#358 @Notnull 삭제
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthVerifyMessageCodeInDTO.java
Labels: 🐞 BugFix
