Repository CaZaIt/CaZaIt-Server, pull requests merged in 2023-05, with the labels that each got.

#259 Cafe - Token 없이 가능한 API 추가
  src/main/java/shop/cazait/domain/cafe/api/CafeController.java
  src/main/java/shop/cazait/domain/cafe/service/CafeService.java
Labels: 📬 API

#265 거리 계산 오류 해결
  src/main/java/shop/cazait/domain/cafe/service/CafeService.java
  src/main/java/shop/cazait/domain/cafe/service/DistanceService.java
Labels: 🐞 BugFix

#267 NoAuth 추가
  src/main/java/shop/cazait/domain/cafemenu/api/CafeMenuApiController.java
Labels: 📬 API, 🔨 Refactor

#269 메뉴 등록 API 수정
  src/main/java/shop/cazait/domain/cafemenu/api/CafeMenuApiController.java
  src/main/java/shop/cazait/domain/cafemenu/service/CafeMenuService.java
Labels: 📬 API, 🔨 Refactor

#270 [Chore] #268 - favorites DTO 네이밍 변경
  src/main/java/shop/cazait/domain/favorites/api/FavoritesApiController.java
  src/main/java/shop/cazait/domain/favorites/dto/response/FavoritesCreateOutDTO.java
  src/main/java/shop/cazait/domain/favorites/dto/response/FavoritesListOutDTO.java
  src/main/java/shop/cazait/domain/favorites/service/FavoritesService.java
Labels: 🔨 Refactor

#271 [Chore] #268 - Congestion DTO 네이밍 변경
  src/main/java/shop/cazait/domain/congestion/api/CongestionApiController.java
  src/main/java/shop/cazait/domain/congestion/dto/request/CongestionUpdateInDTO.java
  src/main/java/shop/cazait/domain/congestion/dto/response/CongestionUpdateOutDTO.java
  src/main/java/shop/cazait/domain/congestion/service/CongestionService.java
Labels: 🔨 Refactor

#273 [Chore] #268 - PreSignedUrl DTO 네이밍 변경
  src/main/java/shop/cazait/domain/s3/api/S3ApiController.java
  src/main/java/shop/cazait/domain/s3/dto/response/PreSignedUrlCreateOutDTO.java
  src/main/java/shop/cazait/domain/s3/service/S3Service.java
Labels: 🔨 Refactor

#277 중복확인 API 수정
  src/main/java/shop/cazait/domain/user/service/UserService.java
  src/main/java/shop/cazait/global/error/status/SuccessStatus.java
Labels: 🔨 Refactor
