Repository CaZaIt/CaZaIt-Server, pull requests merged in 2023-07, with the labels that each got.

#297 UUID 적용 및 누락된 토큰 검증 API 업데이트
  src/main/generated/querydsl/shop/cazait/domain/master/entity/QMaster.java
  src/main/generated/querydsl/shop/cazait/domain/user/entity/QUser.java
  src/main/java/shop/cazait/domain/auth/dto/UserAuthenticateOutDTO.java
  src/main/java/shop/cazait/domain/cafe/api/CafeController.java
  src/main/java/shop/cazait/domain/cafe/service/CafeService.java
  src/main/java/shop/cazait/domain/cafeimage/api/CafeImageController.java
  src/main/java/shop/cazait/domain/cafeimage/service/CafeImageService.java
  src/main/java/shop/cazait/domain/checklog/api/CheckLogApiController.java
  src/main/java/shop/cazait/domain/checklog/repository/CheckLogRepository.java
  src/main/java/shop/cazait/domain/checklog/service/CheckLogService.java
  src/main/java/shop/cazait/domain/congestion/api/CongestionApiController.java
  src/main/java/shop/cazait/domain/favorites/api/FavoritesApiController.java
  src/main/java/shop/cazait/domain/favorites/repository/FavoritesRepository.java
  src/main/java/shop/cazait/domain/favorites/service/FavoritesService.java
  src/main/java/shop/cazait/domain/master/api/MasterController.java
  src/main/java/shop/cazait/domain/master/dto/response/MasterCreateOutDTO.java
  src/main/java/shop/cazait/domain/master/dto/response/MasterListOutDTO.java
  src/main/java/shop/cazait/domain/master/dto/response/MasterUptateOutDTO.java
  src/main/java/shop/cazait/domain/master/entity/Master.java
  src/main/java/shop/cazait/domain/master/repository/MasterRepository.java
  src/main/java/shop/cazait/domain/master/service/MasterService.java
  src/main/java/shop/cazait/domain/review/api/ReviewApiController.java
  src/main/java/shop/cazait/domain/review/dto/ReviewGetOutDTO.java
  src/main/java/shop/cazait/domain/review/dto/ReviewPostOutDTO.java
  src/main/java/shop/cazait/domain/review/service/ReviewDaoService.java
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/dto/UserCreateOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserDeleteOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserFindOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserUpdateOutDTO.java
  src/main/java/shop/cazait/domain/user/entity/User.java
  src/main/java/shop/cazait/domain/user/repository/UserRepository.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
  src/main/java/shop/cazait/global/config/encrypt/JwtService.java
Labels: 🔨 Refactor, 📚Swagger

#314 카페 API 분리
  src/main/java/shop/cazait/domain/cafe/api/CafeController.java
  src/main/java/shop/cazait/domain/cafe/api/CafeSearchApiController.java
  src/main/java/shop/cazait/domain/cafe/service/CafeSearchService.java
  src/main/java/shop/cazait/domain/cafe/service/CafeService.java
  src/main/java/shop/cazait/domain/favorites/api/FavoritesApiController.java
Labels: 📬 API, 🔨 Refactor

#315 [Chore] #299 - 오타 삭제
  src/main/java/shop/cazait/domain/cafe/service/CafeService.java
Labels: 📬 API

#318 #302 - 유저 비밀번호를 유저 API들에의 Response DTO에서 삭제
  src/main/java/shop/cazait/domain/user/dto/UserCreateOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserDeleteOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserFindOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserUpdateOutDTO.java
Labels: 🔨 Refactor, 📚Swagger

#320 토큰 재발급 API 수정
  src/main/java/shop/cazait/domain/user/entity/User.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
Labels: 🐞 BugFix

#325 아이디 찾기, 비밀번호 찾기(수정) API 기본 구현
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/dto/UserFindAccountNameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserFindAccountNameOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserUpdatePasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserUpdatePasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/entity/User.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
  src/main/java/shop/cazait/global/error/status/ErrorStatus.java
Labels: ✨ Feature, 📬 API, 📚Swagger

#326 아이디 찾기, 비밀번호 변경 API 구현 (2차)
  src/main/java/shop/cazait/domain/auth/api/AuthController.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthSendMessageCodeInFindAccountNameInDTO.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthSendMessageCodeInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthSendMessageCodeInSignUpInDTO.java
  src/main/java/shop/cazait/domain/auth/dto/sens/AuthSendMessageCodeTestOutDTO.java
  src/main/java/shop/cazait/domain/auth/service/AuthService.java
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/dto/UserEnterPasswordInResetPasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserEnterUserInfoInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserEnterUserInfoInResetPasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserFindAccountNameInDTO.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
Labels: ✨ Feature, 🔨 Refactor, 📚Swagger

#327 아이디 찾기, 비밀번호 변경 일부 DTO 명, url 수정
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/dto/UserEnterAccountNameInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserEnterAccountNameInResetPasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserEnterPasswordInResetPasswordInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserEnterPasswordInResetPasswordOutDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserFindAccountNameInDTO.java
  src/main/java/shop/cazait/domain/user/dto/UserFindAccountNameOutDTO.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
Labels: 📬 API, 🔨 Refactor

#332 UserException 상태코드 변경사항 반영
  src/main/java/shop/cazait/global/error/exception/GlobalExceptionHandler.java
Labels: 🔨 Refactor
