Repository CaZaIt/CaZaIt-Server, pull requests merged in 2023-06, with the labels that each got.

#278 카페 조회 시 List<CafeImageRes>가 아닌 List<String>으로 전달
  src/main/java/shop/cazait/domain/cafe/dto/GetCafesRes.java
  src/main/java/shop/cazait/domain/cafe/service/CafeService.java
  src/main/java/shop/cazait/domain/cafeimage/service/CafeImageService.java
Labels: ✨ Feature, 📬 API

#280 Cafe DTO, 메소드 네이밍 변경
  src/main/java/shop/cazait/domain/cafe/api/CafeController.java
  src/main/java/shop/cazait/domain/cafe/dto/CafeCreateInDTO.java
  src/main/java/shop/cazait/domain/cafe/dto/CafeGetOutDTO.java
  src/main/java/shop/cazait/domain/cafe/dto/CafeListOutDTO.java
  src/main/java/shop/cazait/domain/cafe/dto/CafeUpdateOutDTO.java
  src/main/java/shop/cazait/domain/cafe/entity/Cafe.java
  src/main/java/shop/cazait/domain/cafe/service/CafeService.java
  src/main/java/shop/cazait/domain/cafe/service/DistanceService.java
  src/main/java/shop/cazait/domain/cafeimage/api/CafeImageController.java
  src/main/java/shop/cazait/domain/cafeimage/dto/CafeImageGetOutDTO.java
  src/main/java/shop/cazait/domain/cafeimage/service/CafeImageService.java
  src/main/java/shop/cazait/domain/coordinate/service/CoordinateService.java
Labels: 🔨 Refactor

#282 Refactor/favorites
  src/main/java/shop/cazait/domain/congestion/entity/CongestionStatus.java
  src/main/java/shop/cazait/domain/favorites/service/FavoritesService.java
  src/main/java/shop/cazait/global/error/status/ErrorStatus.java
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor

#284 [Chore] #283 - 메소드 네이밍 변경
  src/main/java/shop/cazait/domain/congestion/api/CongestionApiController.java
  src/main/java/shop/cazait/domain/congestion/service/CongestionService.java
Labels: 🔨 Refactor

#285 [Chore] #283 - 메소드 네이밍 변경
  src/main/java/shop/cazait/domain/cafemenu/api/CafeMenuApiController.java
  src/main/java/shop/cazait/domain/cafemenu/service/CafeMenuService.java
Labels: 🔨 Refactor

#287 jwt 토큰 수정사항 반영
  src/main/java/shop/cazait/domain/auth/api/AuthController.java
  src/main/java/shop/cazait/domain/auth/service/AuthService.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
  src/main/java/shop/cazait/global/config/encrypt/AuthenticationInterceptor.java
  src/main/java/shop/cazait/global/config/encrypt/JwtService.java
Labels: 🔨 Refactor

#288 [Chore] #268 - Master DTO 네이밍 변경
  src/main/java/shop/cazait/domain/master/api/MasterController.java
  src/main/java/shop/cazait/domain/master/dto/post/PostMasterLogInReq.java
  src/main/java/shop/cazait/domain/master/dto/post/PostMasterLogInRes.java
  src/main/java/shop/cazait/domain/master/dto/request/MasterCreateInDTO.java
  src/main/java/shop/cazait/domain/master/dto/request/MasterUpdateInDTO.java
  src/main/java/shop/cazait/domain/master/dto/response/MasterCreateOutDTO.java
  src/main/java/shop/cazait/domain/master/dto/response/MasterListOutDTO.java
  src/main/java/shop/cazait/domain/master/dto/response/MasterUptateOutDTO.java
  src/main/java/shop/cazait/domain/master/service/MasterService.java
Labels: 🔨 Refactor

#295 토큰 검증 여부에 따른 API 분류 swagger에 반영
  src/main/java/shop/cazait/global/config/openApi/OpenApiConfig.java
Labels: 🔨 Refactor, 📚Swagger
