Repository CaZaIt/CaZaIt-Server, pull requests merged in 2023-01, with the labels that each got.

#4 [ADD] Entiy 필드 생성
  src/main/java/shop/cazait/domain/cafecongestion/entity/cafeCongestion.java
  src/main/java/shop/cazait/domain/cafecongestion/entity/congestionStatus.java
  src/main/java/shop/cazait/domain/cafefavorites/entity/cafeFavorites.java
  src/main/java/shop/cazait/domain/cafemenu/entity/cafeMenu.java
  src/main/java/shop/cazait/domain/cafevisit/entity/cafeVisit.java
Labels: 💾 DataBase

#11 [ADD] 제약 조건
  src/main/java/shop/cazait/domain/cafecongestion/entity/cafeCongestion.java
  src/main/java/shop/cazait/domain/cafefavorites/entity/cafeFavorites.java
  src/main/java/shop/cazait/domain/cafemenu/entity/cafeMenu.java
  src/main/java/shop/cazait/domain/cafevisit/entity/cafeVisit.java
Labels: 💾 DataBase

#16 [ADD] Master 엔티티 생성 및 연관관계 매핑
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jpa-buddy.xml
  src/main/java/shop/cazait/domain/master/entity/Master.java
Labels: 💾 DataBase

#20 [ADD] Review 엔티티 생성 및 연관관계 매핑
  src/main/java/shop/cazait/domain/review/entity/Review.java
Labels: 💾 DataBase

#21 [ADD] User 엔티티 생성 및 연관 관계 매핑
  src/main/java/shop/cazait/domain/user/entity/User.java
Labels: 💾 DataBase

#14 기타 추가 설정
  src/main/java/shop/cazait/domain/cafecongestion/entity/cafeCongestion.java
  src/main/java/shop/cazait/domain/cafefavorites/entity/cafeFavorites.java
  src/main/java/shop/cazait/domain/cafemenu/entity/cafeMenu.java
  src/main/java/shop/cazait/domain/cafevisit/entity/cafeVisit.java
Labels: 💾 DataBase

#9 [ADD] Cafe Entity 생성
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  src/main/java/shop/cazait/domain/cafe/entity/Cafe.java
Labels: 💾 DataBase

#24 [ADD] Cafe Entity @Column 어노테이션 제거
  src/main/java/shop/cazait/domain/cafe/entity/Cafe.java
Labels: 💾 DataBase

#29 [ADD] Cafe Entity @Builder 어노테이션 변경
  src/main/java/shop/cazait/domain/cafe/entity/Cafe.java
Labels: 💾 DataBase

#25 [ADD] @Builder 어노테이션 사용 방법 변경
  src/main/java/shop/cazait/domain/cafecongestion/entity/CafeCongestion.java
  src/main/java/shop/cazait/domain/cafefavorites/entity/CafeFavorites.java
  src/main/java/shop/cazait/domain/cafemenu/entity/CafeMenu.java
  src/main/java/shop/cazait/domain/cafevisit/entity/CafeVisit.java
Labels: 💾 DataBase

#30 [ADD] User Entity @Builder 어노테이션 사용 방법 변경
  src/main/java/shop/cazait/domain/user/entity/User.java
Labels: 💾 DataBase

#32 [ADD] Master Entity @Builder 어노테이션 사용 방법 변경
  src/main/java/shop/cazait/domain/master/entity/Master.java
Labels: 💾 DataBase

#36 [FIX] Builder ID 필드 삭제
  src/main/java/shop/cazait/domain/review/entity/Review.java
Labels: 💾 DataBase

#44 카페 메뉴 관련 API 기능 구현
  src/main/java/shop/cazait/domain/cafemenu/dto/GetCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PostCafeMenuReq.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PutCafeMenuReq.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PutCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/entity/CafeMenu.java
  src/main/java/shop/cazait/domain/cafemenu/repository/CafeMenuRepository.java
  src/main/java/shop/cazait/domain/cafemenu/service/CafeMenuService.java
Labels: ✨ Feature, 📬 API, 📚Swagger

#46 즐겨찾기 관련 API 구현
  src/main/java/shop/cazait/domain/cafefavorites/api/CafeFavoritesApiController.java
  src/main/java/shop/cazait/domain/cafefavorites/dto/GetCafeFavoritesRes.java
  src/main/java/shop/cazait/domain/cafefavorites/dto/PostCafeFavoritesRes.java
  src/main/java/shop/cazait/domain/cafefavorites/exception/CafeFavoritesErrorStatus.java
  src/main/java/shop/cazait/domain/cafefavorites/exception/CafeFavoritesException.java
  src/main/java/shop/cazait/domain/cafefavorites/repository/CafeFavoritesRepository.java
  src/main/java/shop/cazait/domain/cafefavorites/service/CafeFavoritesService.java
Labels: ✨ Feature, 📬 API, 📚Swagger

#47 최근 본 카페 관련 API 구현
  src/main/java/shop/cazait/domain/cafevisit/api/CafeVisitApiController.java
  src/main/java/shop/cazait/domain/cafevisit/dto/GetCafeVisitRes.java
  src/main/java/shop/cazait/domain/cafevisit/repository/CafeVisitRepository.java
  src/main/java/shop/cazait/domain/cafevisit/service/CafeVisitService.java
Labels: ✨ Feature, 📬 API, 📚Swagger

#45 혼잡도 관련 API 기능 구현
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  src/main/java/shop/cazait/domain/congestion/api/CongestionApiController.java
  src/main/java/shop/cazait/domain/congestion/dto/PostCongestionReq.java
  src/main/java/shop/cazait/domain/congestion/dto/PostCongestionRes.java
  src/main/java/shop/cazait/domain/congestion/entity/Congestion.java
  src/main/java/shop/cazait/domain/congestion/repository/CongestionRepository.java
  src/main/java/shop/cazait/domain/congestion/service/CongestionService.java
Labels: ✨ Feature, 📬 API, 📚Swagger

#60 Cafe Entity에 List<String> imageUrl 추가
  src/main/java/shop/cazait/domain/cafe/api/CafeController.java
  src/main/java/shop/cazait/domain/cafe/api/CafeImageController.java
  src/main/java/shop/cazait/domain/cafe/dto/GetCafeRes.java
  src/main/java/shop/cazait/domain/cafe/dto/PostCafeImageReq.java
  src/main/java/shop/cazait/domain/cafe/dto/PostCafeReq.java
  src/main/java/shop/cazait/domain/cafe/entity/Cafe.java
  src/main/java/shop/cazait/domain/cafe/error/CafeErrorStatus.java
  src/main/java/shop/cazait/domain/cafe/error/CafeException.java
  src/main/java/shop/cazait/domain/cafe/repository/CafeImageRepository.java
  src/main/java/shop/cazait/domain/cafe/repository/CafeRepository.java
  src/main/java/shop/cazait/domain/cafe/service/CafeImageService.java
  src/main/java/shop/cazait/domain/cafe/service/CafeService.java
Labels: 💾 DataBase

#61 Cafe exception 처리 방법 변경
  src/main/java/shop/cazait/domain/cafe/api/CafeController.java
  src/main/java/shop/cazait/domain/cafe/error/CafeException.java
Labels: ✨ Feature, 📬 API

#53 Review 기초 CRUD API 구현
  .gradle/7.6/executionHistory/executionHistory.bin
  .gradle/7.6/executionHistory/executionHistory.lock
  .gradle/7.6/fileHashes/fileHashes.bin
  .gradle/7.6/fileHashes/fileHashes.lock
  .gradle/7.6/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  build/resources/main/application.properties
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  src/main/java/shop/cazait/domain/review/api/ReviewApiController.java
  src/main/java/shop/cazait/domain/review/dto/DelReviewRes.java
  src/main/java/shop/cazait/domain/review/dto/GetReviewRes.java
  src/main/java/shop/cazait/domain/review/dto/GetReviewsRes.java
  src/main/java/shop/cazait/domain/review/dto/PatchReviewReq.java
  src/main/java/shop/cazait/domain/review/dto/PatchReviewRes.java
  src/main/java/shop/cazait/domain/review/dto/PostReviewReq.java
  src/main/java/shop/cazait/domain/review/dto/PostReviewRes.java
  src/main/java/shop/cazait/domain/review/entity/Review.java
  src/main/java/shop/cazait/domain/review/repository/ReviewRepository.java
  src/main/java/shop/cazait/domain/review/requestvalue/SortType.java
  src/main/java/shop/cazait/domain/review/service/ReviewDaoService.java
  src/main/java/shop/cazait/domain/review/service/ReviewProvideService.java
Labels: ✨ Feature, 📬 API

#62 Cafe - CafeImage 연관관계 매핑
  src/main/java/shop/cazait/domain/cafe/entity/Cafe.java
Labels: 💾 DataBase

#68 CheckLog 관련 API 1차 Refactoring
  src/main/java/shop/cazait/domain/cafevisit/api/CafeVisitApiController.java
  src/main/java/shop/cazait/domain/cafevisit/dto/GetCafeVisitRes.java
  src/main/java/shop/cazait/domain/cafevisit/repository/CafeVisitRepository.java
  src/main/java/shop/cazait/domain/cafevisit/service/CafeVisitService.java
  src/main/java/shop/cazait/domain/checklog/api/CheckLogApiController.java
  src/main/java/shop/cazait/domain/checklog/dto/GetCheckLogRes.java
  src/main/java/shop/cazait/domain/checklog/dto/PostCheckLogRes.java
  src/main/java/shop/cazait/domain/checklog/entity/CheckLog.java
  src/main/java/shop/cazait/domain/checklog/repository/CheckLogRepository.java
  src/main/java/shop/cazait/domain/checklog/service/CheckLogService.java
Labels: 📬 API, 🔨 Refactor, 📚Swagger

#58 Master 회원 CRUD 구현 및 Entity 추가사항 수정
  src/main/java/shop/cazait/domain/master/controller/MasterController.java
  src/main/java/shop/cazait/domain/master/dto/get/GetMasterRes.java
  src/main/java/shop/cazait/domain/master/dto/patch/PutMasterReq.java
  src/main/java/shop/cazait/domain/master/dto/patch/PutMasterRes.java
  src/main/java/shop/cazait/domain/master/dto/post/PostMasterReq.java
  src/main/java/shop/cazait/domain/master/dto/post/PostMasterRes.java
  src/main/java/shop/cazait/domain/master/entity/Master.java
  src/main/java/shop/cazait/domain/master/error/MasterException.java
  src/main/java/shop/cazait/domain/master/error/MasterResStatus.java
  src/main/java/shop/cazait/domain/master/repository/MasterRepository.java
  src/main/java/shop/cazait/domain/master/service/MasterService.java
  src/main/java/shop/cazait/global/common/entity/JwtToken.java
  src/main/java/shop/cazait/global/config/encrypt/SHA256.java
Labels: ✨ Feature, 📬 API, 💾 DataBase

#59 User API 기초 로직 구현
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/dto/DeleteUserRes.java
  src/main/java/shop/cazait/domain/user/dto/GetUserRes.java
  src/main/java/shop/cazait/domain/user/dto/PatchUserReq.java
  src/main/java/shop/cazait/domain/user/dto/PatchUserRes.java
  src/main/java/shop/cazait/domain/user/dto/PostLoginReq.java
  src/main/java/shop/cazait/domain/user/dto/PostLoginRes.java
  src/main/java/shop/cazait/domain/user/dto/PostUserReq.java
  src/main/java/shop/cazait/domain/user/dto/PostUserRes.java
  src/main/java/shop/cazait/domain/user/entity/User.java
  src/main/java/shop/cazait/domain/user/repository/UserRepository.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
Labels: ✨ Feature, 📬 API, 📚Swagger

#55 Congestion 관련 API 1차 Refactoring
  .gitignore
  src/main/java/shop/cazait/domain/congestion/api/CongestionApiController.java
  src/main/java/shop/cazait/domain/congestion/dto/PostCongestionReq.java
  src/main/java/shop/cazait/domain/congestion/dto/PostCongestionRes.java
  src/main/java/shop/cazait/domain/congestion/entity/CongestionStatus.java
  src/main/java/shop/cazait/domain/congestion/exception/CongestionErrorStatus.java
  src/main/java/shop/cazait/domain/congestion/exception/CongestionException.java
  src/main/java/shop/cazait/domain/congestion/repository/CongestionRepository.java
  src/main/java/shop/cazait/domain/congestion/service/CongestionService.java
  src/main/java/shop/cazait/global/error/exception/GlobalExceptionHandler.java
Labels: 📬 API, 🔨 Refactor, 📚Swagger

#56 Favorites 관련 API 1차 Refactoring
  src/main/java/shop/cazait/domain/cafefavorites/api/CafeFavoritesApiController.java
  src/main/java/shop/cazait/domain/cafefavorites/dto/GetCafeFavoritesRes.java
  src/main/java/shop/cazait/domain/cafefavorites/dto/PostCafeFavoritesRes.java
  src/main/java/shop/cazait/domain/cafefavorites/exception/CafeFavoritesErrorStatus.java
  src/main/java/shop/cazait/domain/cafefavorites/exception/CafeFavoritesException.java
  src/main/java/shop/cazait/domain/cafefavorites/repository/CafeFavoritesRepository.java
  src/main/java/shop/cazait/domain/cafefavorites/service/CafeFavoritesService.java
  src/main/java/shop/cazait/domain/favorites/api/FavoritesApiController.java
  src/main/java/shop/cazait/domain/favorites/dto/GetFavoritesRes.java
  src/main/java/shop/cazait/domain/favorites/dto/PostFavoritesRes.java
  src/main/java/shop/cazait/domain/favorites/entity/Favorites.java
  src/main/java/shop/cazait/domain/favorites/exception/FavoritesErrorStatus.java
  src/main/java/shop/cazait/domain/favorites/exception/FavoritesException.java
  src/main/java/shop/cazait/domain/favorites/repository/FavoritesRepository.java
  src/main/java/shop/cazait/domain/favorites/service/FavoritesService.java
  src/main/java/shop/cazait/global/error/exception/GlobalExceptionHandler.java
Labels: 📬 API, 🔨 Refactor, 📚Swagger

#69 CafeMenu 관련 API 1차 Refactoring
  src/main/java/shop/cazait/domain/cafemenu/api/CafeMenuApiController.java
  src/main/java/shop/cazait/domain/cafemenu/dto/GetCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PatchCafeMenuReq.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PatchCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PostCafeMenuReq.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PostCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PutCafeMenuReq.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PutCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/exception/CafeMenuErrorStatus.java
  src/main/java/shop/cazait/domain/cafemenu/exception/CafeMenuException.java
  src/main/java/shop/cazait/domain/cafemenu/repository/CafeMenuRepository.java
  src/main/java/shop/cazait/domain/cafemenu/service/CafeMenuService.java
  src/main/java/shop/cazait/global/common/constant/Constant.java
Labels: 📬 API, 🔨 Refactor, 📚Swagger

#73 Review 형식적/논리적 vadliation
  src/main/java/shop/cazait/domain/review/api/ReviewApiController.java
  src/main/java/shop/cazait/domain/review/dto/PatchReviewReq.java
  src/main/java/shop/cazait/domain/review/dto/PostReviewReq.java
  src/main/java/shop/cazait/domain/review/requestvalue/SortType.java
  src/main/java/shop/cazait/domain/review/service/ReviewDaoService.java
  src/main/java/shop/cazait/domain/review/service/ReviewProvideService.java
Labels: ✨ Feature, 📬 API

#75 Master 관련 API 1차 리팩토링
  src/main/java/shop/cazait/domain/master/api/MasterController.java
  src/main/java/shop/cazait/domain/master/controller/MasterController.java
  src/main/java/shop/cazait/domain/master/dto/get/GetMasterRes.java
  src/main/java/shop/cazait/domain/master/dto/patch/PutMasterReq.java
  src/main/java/shop/cazait/domain/master/dto/patch/PutMasterRes.java
  src/main/java/shop/cazait/domain/master/dto/post/PostMasterReq.java
  src/main/java/shop/cazait/domain/master/dto/post/PostMasterRes.java
  src/main/java/shop/cazait/domain/master/entity/Master.java
  src/main/java/shop/cazait/domain/master/error/MasterErrorStatus.java
  src/main/java/shop/cazait/domain/master/error/MasterException.java
  src/main/java/shop/cazait/domain/master/error/MasterResStatus.java
  src/main/java/shop/cazait/domain/master/repository/MasterRepository.java
  src/main/java/shop/cazait/domain/master/service/MasterService.java
  src/main/java/shop/cazait/global/common/entity/JwtToken.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor, 📚Swagger

#74 swagger exmaple 값 추가
  src/main/java/shop/cazait/domain/review/dto/PatchReviewReq.java
  src/main/java/shop/cazait/domain/review/dto/PostReviewReq.java
Labels: 📚Swagger

#79 오류 해결 및 Swagger 설정 변경
  src/main/java/shop/cazait/domain/cafe/entity/Cafe.java
  src/main/java/shop/cazait/domain/cafemenu/api/CafeMenuApiController.java
  src/main/java/shop/cazait/domain/cafemenu/dto/GetCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PatchCafeMenuReq.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PatchCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PostCafeMenuReq.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PostCafeMenuRes.java
  src/main/java/shop/cazait/domain/checklog/dto/GetCheckLogRes.java
  src/main/java/shop/cazait/domain/checklog/dto/PostCheckLogRes.java
  src/main/java/shop/cazait/domain/congestion/api/CongestionApiController.java
  src/main/java/shop/cazait/domain/congestion/dto/PostCongestionReq.java
  src/main/java/shop/cazait/domain/congestion/dto/PostCongestionRes.java
  src/main/java/shop/cazait/domain/congestion/service/CongestionService.java
  src/main/java/shop/cazait/domain/favorites/api/FavoritesApiController.java
  src/main/java/shop/cazait/domain/favorites/dto/GetFavoritesRes.java
  src/main/java/shop/cazait/domain/favorites/dto/PostFavoritesRes.java
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor, 📚Swagger

#87 Cafe 이름으로 찾는 기능 추가 및 cafe dummy field 수정
  src/main/java/shop/cazait/domain/cafe/api/CafeController.java
  src/main/java/shop/cazait/domain/cafe/dto/GetCafeRes.java
  src/main/java/shop/cazait/domain/cafe/dto/PostCafeReq.java
  src/main/java/shop/cazait/domain/cafe/entity/Cafe.java
  src/main/java/shop/cazait/domain/cafe/repository/CafeRepository.java
  src/main/java/shop/cazait/domain/cafe/service/CafeService.java
  src/main/java/shop/cazait/domain/cafeimage/api/CafeImageController.java
  src/main/java/shop/cazait/domain/cafeimage/dto/PostCafeImageReq.java
  src/main/resources/h2/data.sql
Labels: ✨ Feature, 📬 API, 📚Swagger

#93 User 기능 1차 리팩토링
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/dto/DeleteUserRes.java
  src/main/java/shop/cazait/domain/user/dto/GetUserRes.java
  src/main/java/shop/cazait/domain/user/dto/PatchUserReq.java
  src/main/java/shop/cazait/domain/user/dto/PatchUserRes.java
  src/main/java/shop/cazait/domain/user/dto/PostLoginReq.java
  src/main/java/shop/cazait/domain/user/dto/PostLoginRes.java
  src/main/java/shop/cazait/domain/user/dto/PostUserReq.java
  src/main/java/shop/cazait/domain/user/dto/PostUserRes.java
  src/main/java/shop/cazait/domain/user/entity/User.java
  src/main/java/shop/cazait/domain/user/repository/UserRepository.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
  src/main/java/shop/cazait/global/config/encrypt/AuthenticationInterceptor.java
  src/main/java/shop/cazait/global/config/encrypt/JwtService.java
  src/main/java/shop/cazait/global/config/encrypt/NoAuth.java
  src/main/java/shop/cazait/global/config/encrypt/Secret.java
  src/main/java/shop/cazait/global/config/encrypt/WebConfig.java
Labels: ✨ Feature, 🔨 Refactor, 📚Swagger

#97 혼잡도 상태 추가
  src/main/java/shop/cazait/domain/congestion/entity/CongestionStatus.java
Labels: 📬 API, 🔨 Refactor

#96 Valid 어노테이션에 대한 예외 처리 핸들링
  src/main/java/shop/cazait/global/common/response/FailResponse.java
  src/main/java/shop/cazait/global/error/exception/GlobalExceptionHandler.java
  src/main/java/shop/cazait/global/error/exception/ValidException.java
  src/main/java/shop/cazait/global/error/status/ErrorStatus.java
Labels: 📬 API, 🔨 Refactor

#91 S3 적용
  .gitignore
  build.gradle
  src/main/java/shop/cazait/CazaitApplication.java
  src/main/java/shop/cazait/global/config/s3/AwsS3Config.java
  src/main/java/shop/cazait/global/util/s3/AwsS3Service.java
  src/main/resources/application.yml
Labels: ⚙ Setting

#92 Review 1차 리팩토링 및 버그 수정
  src/main/java/shop/cazait/domain/review/api/ReviewApiController.java
  src/main/java/shop/cazait/domain/review/dto/GetReviewsRes.java
  src/main/java/shop/cazait/domain/review/dto/PatchReviewReq.java
  src/main/java/shop/cazait/domain/review/dto/PostReviewReq.java
  src/main/java/shop/cazait/domain/review/exception/ReviewException.java
  src/main/java/shop/cazait/domain/review/repository/ReviewRepository.java
  src/main/java/shop/cazait/domain/review/requestvalue/SortType.java
  src/main/java/shop/cazait/domain/review/service/ReviewProvideService.java
  src/main/java/shop/cazait/global/error/exception/GlobalExceptionHandler.java
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor, 📚Swagger

#94 카페 메뉴, 즐겨찾기, 조회 기록 관련 API 2차 리팩토링
  src/main/java/shop/cazait/domain/cafemenu/dto/GetCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PatchCafeMenuReq.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PatchCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PostCafeMenuReq.java
  src/main/java/shop/cazait/domain/cafemenu/dto/PostCafeMenuRes.java
  src/main/java/shop/cazait/domain/cafemenu/entity/CafeMenu.java
  src/main/java/shop/cazait/domain/cafemenu/service/CafeMenuService.java
  src/main/java/shop/cazait/domain/checklog/dto/GetCheckLogRes.java
  src/main/java/shop/cazait/domain/congestion/service/CongestionService.java
  src/main/java/shop/cazait/domain/favorites/dto/GetFavoritesRes.java
  src/main/java/shop/cazait/global/common/constant/Constant.java
Labels: 📬 API, 🔨 Refactor
