Repository CaZaIt/CaZaIt-Server, pull requests merged in 2023-03, with the labels that each got.

#229 유저, 인증 관련 swagger, 기능 구현 수정 및 리팩터링
  build.gradle
  src/main/java/shop/cazait/CazaitApplication.java
  src/main/java/shop/cazait/domain/auth/KakaoIntegrated.java
  src/main/java/shop/cazait/domain/auth/api/AuthController.java
  src/main/java/shop/cazait/domain/auth/client/KakaoClient.java
  src/main/java/shop/cazait/domain/auth/config/KakaoFeignConfiguration.java
  src/main/java/shop/cazait/domain/auth/dto/KakaoAccount.java
  src/main/java/shop/cazait/domain/auth/dto/KakaoCode.java
  src/main/java/shop/cazait/domain/auth/dto/KakaoInfo.java
  src/main/java/shop/cazait/domain/auth/dto/KakaoToken.java
  src/main/java/shop/cazait/domain/auth/dto/Profile.java
  src/main/java/shop/cazait/domain/auth/service/AuthService.java
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/entity/User.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
  src/main/java/shop/cazait/global/config/encrypt/JwtService.java
  src/main/java/shop/cazait/global/config/openApi/OpenApiConfig.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor, 📚Swagger

#230 즐겨찾기 삭제 로직 리팩토링
  src/main/java/shop/cazait/domain/favorites/api/FavoritesApiController.java
  src/main/java/shop/cazait/domain/favorites/repository/FavoritesRepository.java
  src/main/java/shop/cazait/domain/favorites/service/FavoritesService.java
Labels: 📬 API, 🔨 Refactor

#231 즐겨찾기 삭제 스웨거 설정 변경
  src/main/java/shop/cazait/domain/favorites/api/FavoritesApiController.java
Labels: 📚Swagger

#235 오류 해결을 위한 코드 추가
  src/main/java/shop/cazait/global/common/service/AwsS3Service.java
Labels: 🐞 BugFix, 📬 API

#239 [Refactor] #234 - 오류 해결을 위한 코드 추가
  src/main/java/shop/cazait/global/common/service/AwsS3Service.java
Labels: 🐞 BugFix, 📬 API

#242 [Refactor] #234 - 오류 해결을 위한 리팩토링
  src/main/java/shop/cazait/global/common/service/AwsS3Service.java
Labels: 🐞 BugFix, 📬 API

#244 오류 해결을 위한 리팩토링
  src/main/java/shop/cazait/global/common/service/AwsS3Service.java
Labels: 🐞 BugFix, 📬 API

#245 [Refactor] #234 - 오류 해결을 위한 코드 리팩토링
  src/main/java/shop/cazait/global/common/service/AwsS3Service.java
Labels: 🐞 BugFix, 📬 API

#246 Master 토큰 사용 불가 오류 해결 및 Validation 구현
  src/main/java/shop/cazait/domain/master/api/MasterController.java
  src/main/java/shop/cazait/domain/master/dto/patch/PatchMasterReq.java
  src/main/java/shop/cazait/domain/master/dto/post/PostMasterRes.java
  src/main/java/shop/cazait/domain/master/repository/MasterRepository.java
  src/main/java/shop/cazait/domain/master/service/MasterService.java
Labels: 🐞 BugFix, 🔨 Refactor

#248 인터셉터 & 중복확인 api 수정
  src/main/java/shop/cazait/domain/user/api/UserApiController.java
  src/main/java/shop/cazait/domain/user/dto/PostCheckDuplicateEmailReq.java
  src/main/java/shop/cazait/domain/user/dto/PostCheckDuplicateNicknameReq.java
  src/main/java/shop/cazait/domain/user/service/UserService.java
  src/main/java/shop/cazait/global/config/encrypt/AuthenticationInterceptor.java
  src/main/java/shop/cazait/global/config/encrypt/JwtService.java
  src/main/java/shop/cazait/global/config/encrypt/WebConfig.java
  src/main/java/shop/cazait/global/error/exception/GlobalExceptionHandler.java
Labels: 🐞 BugFix, ✨ Feature, 📬 API, 🔨 Refactor, 📚Swagger

#254 [Refactor] #234 - 오류 해결을 위한 코드 리팩토링
  src/main/java/shop/cazait/global/common/service/AwsS3Service.java
  src/main/java/shop/cazait/global/config/s3/AwsS3Config.java
Labels: 🐞 BugFix

#255 [Feat] #234 - s3 이미지 업로드, 객체 조회 기능 구현
  src/main/java/shop/cazait/domain/s3/api/S3ApiController.java
  src/main/java/shop/cazait/domain/s3/dto/GetPreSignedUrlRes.java
  src/main/java/shop/cazait/domain/s3/service/S3Service.java
  src/main/java/shop/cazait/global/common/service/AwsS3Service.java
  src/main/java/shop/cazait/global/config/openApi/OpenApiConfig.java
  src/main/java/shop/cazait/global/config/s3/AwsS3Config.java
Labels: 🐞 BugFix, ✨ Feature, 📬 API, 🔨 Refactor

#257 Master API Validation 및 Refresh Token 검토
  src/main/java/shop/cazait/domain/master/api/MasterController.java
  src/main/java/shop/cazait/domain/master/service/MasterService.java
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor
